### ISSUE TITLE
Abandoned

### ISSUE THREAD

**Issue by toddwc** [clipto-pro/Android#104]
I consider anything that hasn't been updated in a year to be abandoned. It appears that it was mostly a pandemic-era project that proved unprofitable by Autumn 2021.

It likely didn't help that the developer insisted on the silly "rune" labels. While I skip those for the traditional settings screen, newbies might not know how to skip the "runes" page.

It's also too expensive in a recession to pay for the syncing of the number of clips I have, making this app, in practical terms, only functional on one device. 

So . . . I do wish that the developer will very soon make one last update that freely syncs an unlimited number of clips among an unlimited number of devices via cloud storage services like Google Drive.

**Comment by atrashler** [comment]
Nah. There will not be such update:)
Google Drive is technically useless and does not let to sync instantly. So
it would fully kill the main idea of the app.

Runes are just labels (I do not know who cares about these labels and
decide to use the app or not just because of that).
As I know from the feedback, no one actually cares about these labels -
everyone who uses the app understands its functionality and labels do not
change user's opinion to use the app or not.

The idea of the app was not to make it profitable (because it is too
specific area), but to make it useful (which was achieved).
Firestore allows to make it useful, but it requires to pay that is why the
paid options were introduced.
Even 300 free notes are not free to sync in terms of Firestore, but Clipto
allows it, because current subscribers and supporters let to cover these
bills.

The reason why I do not update it is because of my migration and changed
plans due to events following after pandemic (the war).

Maybe I will continue to update it in the future, maybe not, now depends
not only on me, but the app is working and to make it work requires me do
something in the background (usually users do not see it, nevermind).

Anyways, the current functionality of the app covers the most user cases of
using the app.
And to close the discussion about possible change to any other free cloud
provider:
Clipto will never use Google Drive or any other service, which does not let
you sync data instantly.

P.S.: If someone needs to use the app for free, I always give an extended
limit to such people. They just write me an email as it is described on
site...

**Comment by d0x360** [comment]
He's in Ukraine and still paying the bills and the app works
