### ISSUE TITLE
copy on touch

### ISSUE THREAD

**Issue by atrashler** [clipto-pro/Android#3]
instead of opening the note on touch let the ability to copy it into the clipboard

**Comment by roamerhappiness** [comment]
### Intuitive Copying Of Clips

Since the app will be mostly used for copying clips already created, it makes more sense to copy clips by tapping the clip itself instead of clicking the double-paper icon on the right. I would recommend an option where the interface changes. The new interface would have a pencil icon on the right instead of the double-paper icon. The pencil icon would take you to the area where you edit the clip while clicking the clip itself would copy the clip. Basically switching the place of the two functions. This will make the app more efficient and more intuitive and will save users from missing when they try to copy by using the icon in the current design. I acknowledge that you could still misstap when trying to edit although I believe you would edit clips much less often then you would copy them so overall it would save some time and hassle for users.

[https://youtu.be/6zBr50g1Ze4](https://youtu.be/6zBr50g1Ze4)

(hold ctrl to open in new tab)

<a href="https://youtu.be/6zBr50g1Ze4">![ezgif com-gif-maker](https://user-images.githubusercontent.com/55665696/65823635-e976f500-e227-11e9-9439-e7ad2fd7d585.gif)</a>

**Comment by salman-q** [comment]
Make this as one of the options, not the only option since I don't use it for clipping. I am using it as an alternative to Google Keep and I am assuming many people are using this as a traditional note app.

**Comment by atrashler** [comment]
Do you need it for any of existing “List Styles” or only for the specific ones

Need to think how to do it more useful and understandable so it can not break the existing logic. The same behavior was asked to be implemented in the Desktop app also:)

**Comment by salman-q** [comment]
It is useless for me. I can just tap copy button when I need to copy a note. I find myself opening the notes a lot so the current tap to open note is the ideal solution.

**Comment by atrashler** [comment]
I also prefer not to mix the functionality. But why not to ask @roamerhappiness as the author of the request. Probably he stopped using the app since such a long period of time and this task is not actual anymore:)
