### ISSUE TITLE
What license is your sourcecode here?

### ISSUE THREAD

**Issue by 5TDg9** [clipto-pro/Android#32]
Hello dear developers!
You write "Community driven" in readme.md
but you don't mention any license?

**Comment by atrashler** [comment]
1) Community-driven means that everyone can suggest features and drive the development in such way. I can not let everyone to develop the parts of the product because it will impact the final quality of it.
2) I can not open-source it now because everyone who has minimal marketing skills can put ads, change title and sell it. It will impact the reputation of the whole product and on the current stage it is better not to do it. The product should have at least few million installs to not be used in such way.
3) If you have such questions then probably you have some skills to decompile the Android app or Web scripts to understand how it works under the hood and check for any security issues.
The product is not something that could be promoted by big companies, but could be used by some ‘developers’ who can easily recompile it to ‘yet another notepad and clipboard app’. Now Clipto is not ready for it, as I have mentioned. I just care about the quality of the product, not the speed of the development process. When Clipto is ready for it, it will be open sourced:)
Thanks for your question!

**Comment by 5TDg9** [comment]
Thanks for clarification. Especially point 3 sound trustful to me. And in the end that's what it all is about.

**Comment by cauerego** [comment]
i personally think it should be open sourced anyway. always. http://cregox.net/open

the only reason i didn't uninstall it just now and then completely turned my back to it, before finding this information, is because i had tried a lot of clipboard history apps, and this has been the best one for months, and so i looked hard to find the source.

however...

> The product should have at least few million installs to not be used in such way. (abused by competition and ruin the product image)

that's an interesting point of view. what makes you say that? any experience in specific?

because, in my point of view, this just can't happen in practice. for instance: phonograph. i learned about it through one of its mostly useless forks (honestly can't remember which one). almost all of its forks do exactly what you fear. but i even end up using one of them (music) because it just works better for me.

the only concern i would have, in your place, is gathering all those good forks around, talking to them, and joining forces rather than spreading so much energy. focusing all that dev power into one main source makes so much more sense... but that's already offtopic here. 😁

**Comment by atrashler** [comment]
> i personally think it should be open sourced anyway. always. http://cregox.net/open
> 
> the only reason i didn't uninstall it just now and then completely turned my back to it, before finding this information, is because i had tried a lot of clipboard history apps, and this has been the best one for months, and so i looked hard to find the source.
> 
> however...
> 
> > The product should have at least few million installs to not be used in such way. (abused by competition and ruin the product image)
> 
> that's an interesting point of view. what makes you say that? any experience in specific?
> 
> because, in my point of view, this just can't happen in practice. for instance: phonograph. i learned about it through one of its mostly useless forks (honestly can't remember which one). almost all of its forks do exactly what you fear. but i even end up using one of them (music) because it just works better for me.
> 
> the only concern i would have, in your place, is gathering all those good forks around, talking to them, and joining forces rather than spreading so much energy. focusing all that dev power into one main source makes so much more sense... but that's already offtopic here. 😁

ClipStack was open sourced for few months. It was copied several times and published on Google Play with exactly the same functionality but full of ads. Me or the author of the mentioned app do not have resources for juridical support for such scenarios.
