### ISSUE TITLE
Deleted my local database, on tablet (8000 --> 400 articles)

### ISSUE THREAD

**Issue by xpareto** [clipto-pro/Android#46]
Now, it grows ...but my 8000 items? . A week ago.
On my phone.. remained at 6000.

**Comment by atrashler** [comment]
And you have been authorized and all your notes were correctly synced with the cloud (means that you did not prevent the app from sync by any external apps that could lead to any hidden issues), right? Could you send your account id and app details (go to app settings -> scroll down -> click on Email action)

**Comment by xpareto** [comment]
Thank You for your speed of reaction.

I think it has some link with the new limit of syncronization.
I hope one mail come to you.
Thank You.

**Comment by atrashler** [comment]
the limit does not affect any existing data no matter how many of data you have. For all new data you will see the red icon “not synchronized” both in the list and note”s screen.

**Comment by xpareto** [comment]
The problem appeared some time after the aparition of the idea off limit. I
dont't know how  the minimum number was. I observed when it was 4xx? and
growing (From then) . Maybe after "optimisation" ? sorry but I cannot be
more specific. Maybe the mail from settings (I am not sure it it worked).
 Your affirmation about how the limit should fonction does not fix my
problem. But I understand I am alone and you have a lot of work to do .

On Tuesday, July 14, 2020, Alex Trashler <notifications@github.com> wrote:
> Closed #46.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/MgafrgfE82a482jE6gzIYlU8dj1kXysbZR2Of18Znu-I5Nax48jK6F1Y6l1ULJnInzWSVgfWsBK3s2qY4u4bmj-zKKDTyfLllxT9z7V-DeHytyr_gY-Lad-LOPYSeO35hvRSKqctFysRZrPd7o3dP3uH2YLNV-AVxnL_ZX8B6Euyu1qAI2uh6vzYc8_80iOoij3y-Y_nOkB8asqqgEHrVfhYJV-XRfoeYyNvn-hqKJXKuvVegXO8Il76-8XavgI=s0-d-e1-ft#https://github.com/notifications/beacon/ABCXWSWEVIBSLVU6PO7PUVTR3S3SZA5CNFSM4OZQ5Q22YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGO2NL25XQ.gif>

**Comment by atrashler** [comment]
Optimization was turned off due to found issues in this functionality. So if you have passed it once then the latest version of the app should ask you to pass it again to revert all made changes.

Also, while using the app be also aware about functional changes: the notes from the clipboard do not synchronized automatically across all your devices (and with the cloud) if you do not activate the setting “universal clipboard”. You will also see the same red icon “not synchronized” for each of such notes. It is done because some of the users do not like that the app sync their clipboard automatically, so I have added an extra condition to make it happens.
